# Generated by Django 2.2 on 2021-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('new_image', models.ImageField(upload_to='gallery_folder')),
                ('day_publish', models.DateField()),
            ],
        ),
    ]
