# Generated by Django 2.2 on 2021-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_1', models.CharField(max_length=250)),
                ('main_image', models.ImageField(upload_to='home_page')),
                ('main_image_alt', models.CharField(max_length=250)),
                ('stinger_about', models.TextField()),
                ('stinger_logo', models.ImageField(upload_to='home_page')),
                ('stinger_special_offer', models.TextField()),
                ('stinger_special_offer_image', models.ImageField(upload_to='home_page')),
            ],
        ),
    ]
